<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Logic.Foundation.PreviewManagement\Logic.Foundation.PreviewManagement.csproj" />
    <ProjectReference Include="..\..\..\plugins\plugin_time_travelers\plugin_time_travelers.csproj" Aliases="timetravelers" />
    <ProjectReference Include="..\..\..\plugins\plugin_yokai_watch\plugin_yokai_watch.csproj" Aliases="yokai" />
  </ItemGroup>

</Project>
