using System.Text;

namespace Logic.Foundation.PreviewManagement.Generators;

internal static class PreviewPluginAbiEmitter
{
    public static string Emit(IReadOnlyList<PluginModel> plugins, IReadOnlyList<CharacterTypeModel> characters)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Buffers.Binary;");
        builder.AppendLine("using System.Runtime.CompilerServices;");
        builder.AppendLine("using System.Runtime.InteropServices;");
        builder.AppendLine("using System.Text;");
        builder.AppendLine();
        builder.AppendLine("namespace Logic.Foundation.PreviewManagement.Generated;");
        builder.AppendLine();
        EmitWire(builder, characters);
        builder.AppendLine();
        EmitExports(builder, plugins);
        return builder.ToString();
    }

    private static void EmitWire(StringBuilder builder, IReadOnlyList<CharacterTypeModel> characters)
    {
        builder.AppendLine("public static class PreviewCharacterWire");
        builder.AppendLine("{");
        builder.AppendLine("    public static byte[] Write(global::System.Collections.Generic.IList<global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData> characters)");
        builder.AppendLine("    {");
        builder.AppendLine("        var buffer = new global::System.Collections.Generic.List<byte>();");
        builder.AppendLine("        WriteInt32(buffer, characters.Count);");
        builder.AppendLine("        foreach (global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData character in characters)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (character)");
        builder.AppendLine("            {");
        foreach (CharacterTypeModel character in characters)
            EmitWriteCase(builder, character);
        builder.AppendLine("                default:");
        builder.AppendLine("                    throw new global::System.InvalidOperationException(\"Unsupported character type \" + character.GetType().FullName);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return buffer.ToArray();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Collections.Generic.List<global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData> Read(global::System.ReadOnlySpan<byte> data)");
        builder.AppendLine("    {");
        builder.AppendLine("        int offset = 0;");
        builder.AppendLine("        int count = ReadInt32(data, ref offset);");
        builder.AppendLine("        var characters = new global::System.Collections.Generic.List<global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData>(count);");
        builder.AppendLine("        for (int index = 0; index < count; index++)");
        builder.AppendLine("        {");
        builder.AppendLine("            bool isVisible = ReadBool(data, ref offset);");
        builder.AppendLine("            bool isPersistent = ReadBool(data, ref offset);");
        builder.AppendLine("            uint typeId = ReadUInt32(data, ref offset);");
        builder.AppendLine("            int payloadLength = ReadInt32(data, ref offset);");
        builder.AppendLine("            if (payloadLength < 0 || data.Length - offset < payloadLength)");
        builder.AppendLine("                throw new global::System.InvalidOperationException(\"Truncated character payload.\");");
        builder.AppendLine("            int payloadEnd = offset + payloadLength;");
        builder.AppendLine("            global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData character = typeId switch");
        builder.AppendLine("            {");
        foreach (CharacterTypeModel character in characters)
            EmitReadCase(builder, character);
        builder.AppendLine("                _ => throw new global::System.InvalidOperationException(\"Unsupported character type id \" + typeId.ToString(\"X8\"))");
        builder.AppendLine("            };");
        builder.AppendLine("            if (offset != payloadEnd)");
        builder.AppendLine("                throw new global::System.InvalidOperationException(\"Character payload size does not match type \" + typeId.ToString(\"X8\"));");
        builder.AppendLine("            characters.Add(character);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return characters;");
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitPrimitiveHelpers(builder);
        EmitReadCaseMethods(builder, characters);
        builder.AppendLine("}");
    }

    private static void EmitWriteCase(StringBuilder builder, CharacterTypeModel character)
    {
        builder.AppendLine($"                case {character.QualifiedName} c:");
        builder.AppendLine("                {");
        builder.AppendLine("                    var payload = new global::System.Collections.Generic.List<byte>();");
        foreach (PropertyModel property in character.Properties)
            EmitWriteProperty(builder, property);
        builder.AppendLine($"                    WriteRecord(buffer, c.IsVisible, c.IsPersistent, {character.TypeId}u, payload);");
        builder.AppendLine("                    break;");
        builder.AppendLine("                }");
    }

    private static void EmitWriteProperty(StringBuilder builder, PropertyModel property)
    {
        string access = "c." + property.Name;
        switch (property.Kind)
        {
            case WireKind.Bool:
                builder.AppendLine($"                    WriteBool(payload, {access});");
                break;
            case WireKind.UInt8:
                builder.AppendLine($"                    payload.Add({access});");
                break;
            case WireKind.Int8:
                builder.AppendLine($"                    payload.Add((byte){access});");
                break;
            case WireKind.Int16:
                builder.AppendLine($"                    WriteInt16(payload, {Cast(property, "short", access)});");
                break;
            case WireKind.UInt16:
                builder.AppendLine($"                    WriteUInt16(payload, {Cast(property, "ushort", access)});");
                break;
            case WireKind.Int32:
                builder.AppendLine($"                    WriteInt32(payload, {Cast(property, "int", access)});");
                break;
            case WireKind.UInt32:
                builder.AppendLine($"                    WriteUInt32(payload, {Cast(property, "uint", access)});");
                break;
            case WireKind.Int64:
                builder.AppendLine($"                    WriteInt64(payload, {Cast(property, "long", access)});");
                break;
            case WireKind.UInt64:
                builder.AppendLine($"                    WriteUInt64(payload, {Cast(property, "ulong", access)});");
                break;
            case WireKind.Char:
                builder.AppendLine($"                    WriteUInt16(payload, (ushort){access});");
                break;
            case WireKind.String:
                builder.AppendLine($"                    WriteString(payload, {access});");
                break;
            case WireKind.Single:
                builder.AppendLine($"                    WriteInt32(payload, global::System.BitConverter.SingleToInt32Bits({access}));");
                break;
            case WireKind.Double:
                builder.AppendLine($"                    WriteInt64(payload, global::System.BitConverter.DoubleToInt64Bits({access}));");
                break;
            case WireKind.Rgba32:
                builder.AppendLine($"                    payload.Add({access}.R);");
                builder.AppendLine($"                    payload.Add({access}.G);");
                builder.AppendLine($"                    payload.Add({access}.B);");
                builder.AppendLine($"                    payload.Add({access}.A);");
                break;
        }
    }

    private static string Cast(PropertyModel property, string rawType, string access)
    {
        return property.IsEnum ? $"({rawType}){access}" : access;
    }

    private static void EmitReadCase(StringBuilder builder, CharacterTypeModel character)
    {
        builder.AppendLine($"                {character.TypeId}u => Read_{Sanitize(character.MetadataName)}(data, ref offset, payloadEnd, isVisible, isPersistent),");
    }

    private static void EmitPrimitiveHelpers(StringBuilder builder)
    {
        builder.AppendLine("    private static void WriteRecord(global::System.Collections.Generic.List<byte> buffer, bool isVisible, bool isPersistent, uint typeId, global::System.Collections.Generic.List<byte> payload)");
        builder.AppendLine("    {");
        builder.AppendLine("        buffer.Add(isVisible ? (byte)1 : (byte)0);");
        builder.AppendLine("        buffer.Add(isPersistent ? (byte)1 : (byte)0);");
        builder.AppendLine("        WriteUInt32(buffer, typeId);");
        builder.AppendLine("        WriteInt32(buffer, payload.Count);");
        builder.AppendLine("        buffer.AddRange(payload);");
        builder.AppendLine("    }");
        builder.AppendLine();
        AppendWrite(builder, "WriteBool", "bool value", "buffer.Add(value ? (byte)1 : (byte)0);");
        AppendWrite(builder, "WriteInt16", "short value", "Span<byte> bytes = stackalloc byte[2]; BinaryPrimitives.WriteInt16LittleEndian(bytes, value); buffer.AddRange(bytes.ToArray());");
        AppendWrite(builder, "WriteUInt16", "ushort value", "Span<byte> bytes = stackalloc byte[2]; BinaryPrimitives.WriteUInt16LittleEndian(bytes, value); buffer.AddRange(bytes.ToArray());");
        AppendWrite(builder, "WriteInt32", "int value", "Span<byte> bytes = stackalloc byte[4]; BinaryPrimitives.WriteInt32LittleEndian(bytes, value); buffer.AddRange(bytes.ToArray());");
        AppendWrite(builder, "WriteUInt32", "uint value", "Span<byte> bytes = stackalloc byte[4]; BinaryPrimitives.WriteUInt32LittleEndian(bytes, value); buffer.AddRange(bytes.ToArray());");
        AppendWrite(builder, "WriteInt64", "long value", "Span<byte> bytes = stackalloc byte[8]; BinaryPrimitives.WriteInt64LittleEndian(bytes, value); buffer.AddRange(bytes.ToArray());");
        AppendWrite(builder, "WriteUInt64", "ulong value", "Span<byte> bytes = stackalloc byte[8]; BinaryPrimitives.WriteUInt64LittleEndian(bytes, value); buffer.AddRange(bytes.ToArray());");
        builder.AppendLine("    private static void WriteString(global::System.Collections.Generic.List<byte> buffer, string? value)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (value is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            WriteInt32(buffer, -1);");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        byte[] encoded = Encoding.UTF8.GetBytes(value);");
        builder.AppendLine("        WriteInt32(buffer, encoded.Length);");
        builder.AppendLine("        buffer.AddRange(encoded);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool ReadBool(global::System.ReadOnlySpan<byte> data, ref int offset)");
        builder.AppendLine("    {");
        builder.AppendLine("        return ReadUInt8(data, ref offset) != 0;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static byte ReadUInt8(global::System.ReadOnlySpan<byte> data, ref int offset)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (data.Length - offset < 1)");
        builder.AppendLine("            throw new global::System.InvalidOperationException(\"Truncated character wire.\");");
        builder.AppendLine("        return data[offset++];");
        builder.AppendLine("    }");
        builder.AppendLine();
        AppendRead(builder, "short", "ReadInt16", "BinaryPrimitives.ReadInt16LittleEndian(data.Slice(offset, 2))", 2);
        AppendRead(builder, "ushort", "ReadUInt16", "BinaryPrimitives.ReadUInt16LittleEndian(data.Slice(offset, 2))", 2);
        AppendRead(builder, "int", "ReadInt32", "BinaryPrimitives.ReadInt32LittleEndian(data.Slice(offset, 4))", 4);
        AppendRead(builder, "uint", "ReadUInt32", "BinaryPrimitives.ReadUInt32LittleEndian(data.Slice(offset, 4))", 4);
        AppendRead(builder, "long", "ReadInt64", "BinaryPrimitives.ReadInt64LittleEndian(data.Slice(offset, 8))", 8);
        AppendRead(builder, "ulong", "ReadUInt64", "BinaryPrimitives.ReadUInt64LittleEndian(data.Slice(offset, 8))", 8);
        builder.AppendLine("    private static string? ReadString(global::System.ReadOnlySpan<byte> data, ref int offset)");
        builder.AppendLine("    {");
        builder.AppendLine("        int length = ReadInt32(data, ref offset);");
        builder.AppendLine("        if (length < 0)");
        builder.AppendLine("            return null;");
        builder.AppendLine("        if (data.Length - offset < length)");
        builder.AppendLine("            throw new global::System.InvalidOperationException(\"Truncated character string.\");");
        builder.AppendLine("        string value = Encoding.UTF8.GetString(data.Slice(offset, length));");
        builder.AppendLine("        offset += length;");
        builder.AppendLine("        return value;");
        builder.AppendLine("    }");
    }

    private static void EmitReadCaseMethods(StringBuilder builder, IReadOnlyList<CharacterTypeModel> characters)
    {
        foreach (CharacterTypeModel character in characters)
        {
            builder.AppendLine();
            builder.AppendLine($"    private static {character.QualifiedName} Read_{Sanitize(character.MetadataName)}(global::System.ReadOnlySpan<byte> data, ref int offset, int payloadEnd, bool isVisible, bool isPersistent)");
            builder.AppendLine("    {");
            foreach (PropertyModel property in character.Properties)
                EmitReadProperty(builder, property);
            builder.AppendLine("        if (offset != payloadEnd)");
            builder.AppendLine($"            throw new global::System.InvalidOperationException(\"Character payload size does not match {character.MetadataName}.\");");
            builder.AppendLine($"        return new {character.QualifiedName}");
            builder.AppendLine("        {");
            builder.AppendLine("            IsVisible = isVisible,");
            builder.AppendLine("            IsPersistent = isPersistent,");
            foreach (PropertyModel property in character.Properties)
                builder.AppendLine($"            {property.Name} = value_{property.Name},");
            builder.AppendLine("        };");
            builder.AppendLine("    }");
        }
    }

    private static void EmitReadProperty(StringBuilder builder, PropertyModel property)
    {
        string local = "value_" + property.Name;
        switch (property.Kind)
        {
            case WireKind.Bool:
                builder.AppendLine($"        bool {local} = ReadBool(data, ref offset);");
                break;
            case WireKind.UInt8:
                Assign(builder, property, local, "ReadUInt8(data, ref offset)");
                break;
            case WireKind.Int8:
                Assign(builder, property, local, "(sbyte)ReadUInt8(data, ref offset)");
                break;
            case WireKind.Int16:
                Assign(builder, property, local, "ReadInt16(data, ref offset)");
                break;
            case WireKind.UInt16:
                Assign(builder, property, local, "ReadUInt16(data, ref offset)");
                break;
            case WireKind.Int32:
                Assign(builder, property, local, "ReadInt32(data, ref offset)");
                break;
            case WireKind.UInt32:
                Assign(builder, property, local, "ReadUInt32(data, ref offset)");
                break;
            case WireKind.Int64:
                Assign(builder, property, local, "ReadInt64(data, ref offset)");
                break;
            case WireKind.UInt64:
                Assign(builder, property, local, "ReadUInt64(data, ref offset)");
                break;
            case WireKind.Char:
                builder.AppendLine($"        char {local} = (char)ReadUInt16(data, ref offset);");
                break;
            case WireKind.String:
                builder.AppendLine($"        string {local} = ReadString(data, ref offset) ?? string.Empty;");
                break;
            case WireKind.Single:
                builder.AppendLine($"        float {local} = global::System.BitConverter.Int32BitsToSingle(ReadInt32(data, ref offset));");
                break;
            case WireKind.Double:
                builder.AppendLine($"        double {local} = global::System.BitConverter.Int64BitsToDouble(ReadInt64(data, ref offset));");
                break;
            case WireKind.Rgba32:
                builder.AppendLine($"        byte {local}_R = ReadUInt8(data, ref offset);");
                builder.AppendLine($"        byte {local}_G = ReadUInt8(data, ref offset);");
                builder.AppendLine($"        byte {local}_B = ReadUInt8(data, ref offset);");
                builder.AppendLine($"        byte {local}_A = ReadUInt8(data, ref offset);");
                builder.AppendLine($"        {property.QualifiedType} {local} = new {property.QualifiedType}({local}_R, {local}_G, {local}_B, {local}_A);");
                break;
        }
    }

    private static void Assign(StringBuilder builder, PropertyModel property, string local, string expression)
    {
        if (property.IsEnum)
            builder.AppendLine($"        {property.QualifiedType} {local} = ({property.QualifiedType}){expression};");
        else if (property.Kind == WireKind.UInt16 && property.QualifiedType.EndsWith("System.Char", StringComparison.Ordinal))
            builder.AppendLine($"        char {local} = (char){expression};");
        else
            builder.AppendLine($"        {RawType(property.Kind)} {local} = {expression};");
    }

    private static string RawType(WireKind kind)
    {
        return kind switch
        {
            WireKind.Bool => "bool",
            WireKind.UInt8 => "byte",
            WireKind.Int8 => "sbyte",
            WireKind.Int16 => "short",
            WireKind.UInt16 => "ushort",
            WireKind.Int32 => "int",
            WireKind.UInt32 => "uint",
            WireKind.Int64 => "long",
            WireKind.UInt64 => "ulong",
            WireKind.Char => "char",
            WireKind.String => "string",
            WireKind.Single => "float",
            WireKind.Double => "double",
            _ => "byte"
        };
    }

    private static void EmitExports(StringBuilder builder, IReadOnlyList<PluginModel> plugins)
    {
        builder.AppendLine("public static unsafe class PreviewPluginAbi");
        builder.AppendLine("{");
        builder.AppendLine("    private static string? _lastError;");
        builder.AppendLine("    private static readonly global::Logic.Foundation.PreviewManagement.Abstract.IPreviewPlugin[] Plugins =");
        builder.AppendLine("    [");
        foreach (PluginModel plugin in plugins)
            builder.AppendLine($"        new {plugin.QualifiedName}(),");
        builder.AppendLine("    ];");
        builder.AppendLine();
        EmitExport(builder, "cbe_plugin_get_count", "public static int GetCount()", "        return Plugins.Length;");
        builder.AppendLine();
        builder.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"cbe_plugin_get_id\", CallConvs = new[] { typeof(CallConvCdecl) })]");
        builder.AppendLine("    public static int GetId(int index, global::System.Guid* pluginId)");
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            _lastError = null;");
        builder.AppendLine("            if (pluginId == null || (uint)index >= (uint)Plugins.Length)");
        builder.AppendLine("                return 1;");
        builder.AppendLine("            *pluginId = Plugins[index].PluginId;");
        builder.AppendLine("            return 0;");
        builder.AppendLine("        }");
        builder.AppendLine("        catch (global::System.Exception exception)");
        builder.AppendLine("        {");
        builder.AppendLine("            _lastError = exception.ToString();");
        builder.AppendLine("            return 2;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitBufferExport(
            builder,
            "cbe_plugin_get_metadata",
            "public static int GetMetadata(int index, ByteBuffer* output)",
            """
                        if (output == null || (uint)index >= (uint)Plugins.Length)
                            return 1;
                        *output = Allocate(MetadataJson(Plugins[index]));
                        return 0;
            """);
        builder.AppendLine();
        EmitBufferExport(
            builder,
            "cbe_plugin_deserialize",
            "public static int Deserialize(int index, byte* text, int textLength, ByteBuffer* output)",
            """
                        if (output == null || (uint)index >= (uint)Plugins.Length || textLength < 0)
                            return 1;
                        string value = textLength == 0 ? string.Empty : Encoding.UTF8.GetString(text, textLength);
                        global::Logic.Foundation.PreviewManagement.Abstract.IPreviewPlugin plugin = Plugins[index];
                        global::Kaligraphy.Contract.Parsing.ICharacterDeserializer deserializer = plugin.Deserializer ?? new global::Kaligraphy.Parsing.CharacterDeserializer();
                        global::System.Collections.Generic.IList<global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData> characters = deserializer.Deserialize(value);
                        *output = Allocate(PreviewCharacterWire.Write(characters));
                        return 0;
            """);
        builder.AppendLine();
        EmitBufferExport(
            builder,
            "cbe_plugin_render",
            "public static int Render(int index, byte* wire, int wireLength, ByteBuffer* output)",
            """
                        if (output == null || (uint)index >= (uint)Plugins.Length || wireLength < 0)
                            return 1;
                        global::System.ReadOnlySpan<byte> wireBytes = wireLength == 0 ? global::System.ReadOnlySpan<byte>.Empty : new global::System.ReadOnlySpan<byte>(wire, wireLength);
                        global::System.Collections.Generic.List<global::Kaligraphy.Contract.DataClasses.Parsing.CharacterData> characters = PreviewCharacterWire.Read(wireBytes);
                        global::SixLabors.ImageSharp.Image<global::SixLabors.ImageSharp.PixelFormats.Rgba32>? image = Plugins[index].RenderPreview(characters).GetAwaiter().GetResult();
                        *output = Allocate(EncodeImage(image));
                        return 0;
            """);
        builder.AppendLine();
        builder.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"cbe_plugin_get_last_error\", CallConvs = new[] { typeof(CallConvCdecl) })]");
        builder.AppendLine("    public static int GetLastError(ByteBuffer* output)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (output == null)");
        builder.AppendLine("            return 1;");
        builder.AppendLine("        *output = Allocate(Encoding.UTF8.GetBytes(_lastError ?? string.Empty));");
        builder.AppendLine("        return 0;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"cbe_plugin_free\", CallConvs = new[] { typeof(CallConvCdecl) })]");
        builder.AppendLine("    public static void Free(void* ptr)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (ptr != null)");
        builder.AppendLine("            NativeMemory.Free(ptr);");
        builder.AppendLine("    }");
        builder.AppendLine();
        EmitSupport(builder);
        builder.AppendLine("}");
    }

    private static void EmitExport(StringBuilder builder, string entryPoint, string signature, string body)
    {
        builder.AppendLine($"    [UnmanagedCallersOnly(EntryPoint = \"{entryPoint}\", CallConvs = new[] {{ typeof(CallConvCdecl) }})]");
        builder.AppendLine($"    {signature}");
        builder.AppendLine("    {");
        builder.AppendLine(body);
        builder.AppendLine("    }");
    }

    private static void EmitBufferExport(StringBuilder builder, string entryPoint, string signature, string successBody)
    {
        builder.AppendLine($"    [UnmanagedCallersOnly(EntryPoint = \"{entryPoint}\", CallConvs = new[] {{ typeof(CallConvCdecl) }})]");
        builder.AppendLine($"    {signature}");
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            _lastError = null;");
        builder.AppendLine(successBody);
        builder.AppendLine("        }");
        builder.AppendLine("        catch (global::System.Exception exception)");
        builder.AppendLine("        {");
        builder.AppendLine("            _lastError = exception.ToString();");
        builder.AppendLine("            return 2;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void EmitSupport(StringBuilder builder)
    {
        builder.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
        builder.AppendLine("    public struct ByteBuffer");
        builder.AppendLine("    {");
        builder.AppendLine("        public global::System.IntPtr Data;");
        builder.AppendLine("        public int Length;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static ByteBuffer Allocate(byte[] data)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (data.Length == 0)");
        builder.AppendLine("            return default;");
        builder.AppendLine("        void* memory = NativeMemory.Alloc((nuint)data.Length);");
        builder.AppendLine("        fixed (byte* source = data)");
        builder.AppendLine("            Buffer.MemoryCopy(source, memory, data.Length, data.Length);");
        builder.AppendLine("        return new ByteBuffer { Data = (global::System.IntPtr)memory, Length = data.Length };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static byte[] EncodeImage(global::SixLabors.ImageSharp.Image<global::SixLabors.ImageSharp.PixelFormats.Rgba32>? image)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (image is null)");
        builder.AppendLine("            return global::System.Array.Empty<byte>();");
        builder.AppendLine("        int width = image.Width;");
        builder.AppendLine("        int height = image.Height;");
        builder.AppendLine("        byte[] buffer = new byte[8 + width * height * 4];");
        builder.AppendLine("        BinaryPrimitives.WriteInt32LittleEndian(buffer, width);");
        builder.AppendLine("        BinaryPrimitives.WriteInt32LittleEndian(buffer.AsSpan(4), height);");
        builder.AppendLine("        int offset = 8;");
        builder.AppendLine("        image.ProcessPixelRows(accessor =>");
        builder.AppendLine("        {");
        builder.AppendLine("            for (int y = 0; y < height; y++)");
        builder.AppendLine("            {");
        builder.AppendLine("                global::System.Span<global::SixLabors.ImageSharp.PixelFormats.Rgba32> row = accessor.GetRowSpan(y);");
        builder.AppendLine("                for (int x = 0; x < width; x++)");
        builder.AppendLine("                {");
        builder.AppendLine("                    buffer[offset++] = row[x].R;");
        builder.AppendLine("                    buffer[offset++] = row[x].G;");
        builder.AppendLine("                    buffer[offset++] = row[x].B;");
        builder.AppendLine("                    buffer[offset++] = row[x].A;");
        builder.AppendLine("                }");
        builder.AppendLine("            }");
        builder.AppendLine("        });");
        builder.AppendLine("        return buffer;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static byte[] MetadataJson(global::Logic.Foundation.PreviewManagement.Abstract.IPreviewPlugin plugin)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::Konnect.Contract.DataClasses.Plugin.PluginMetadata metadata = plugin.Metadata;");
        builder.AppendLine("        var json = new StringBuilder();");
        builder.AppendLine("        json.Append('{');");
        builder.AppendLine("        AppendField(json, \"name\", metadata.Name, first: true);");
        builder.AppendLine("        AppendField(json, \"author\", metadata.Author);");
        builder.AppendLine("        AppendField(json, \"platform\", metadata.Platform);");
        builder.AppendLine("        AppendField(json, \"developer\", metadata.Developer);");
        builder.AppendLine("        AppendField(json, \"publisher\", metadata.Publisher);");
        builder.AppendLine("        AppendField(json, \"longDescription\", metadata.LongDescription);");
        builder.AppendLine("        AppendField(json, \"shortDescription\", metadata.ShortDescription);");
        builder.AppendLine("        AppendField(json, \"website\", metadata.Website);");
        builder.AppendLine("        json.Append('}');");
        builder.AppendLine("        return Encoding.UTF8.GetBytes(json.ToString());");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void AppendField(StringBuilder json, string name, string? value, bool first = false)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!first)");
        builder.AppendLine("            json.Append(',');");
        builder.AppendLine("        json.Append('\"').Append(name).Append('\"').Append(':');");
        builder.AppendLine("        AppendString(json, value);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void AppendField(StringBuilder json, string name, string[]? values)");
        builder.AppendLine("    {");
        builder.AppendLine("        json.Append(',').Append('\"').Append(name).Append('\"').Append(':').Append('[');");
        builder.AppendLine("        if (values is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            for (int index = 0; index < values.Length; index++)");
        builder.AppendLine("            {");
        builder.AppendLine("                if (index > 0)");
        builder.AppendLine("                    json.Append(',');");
        builder.AppendLine("                AppendString(json, values[index]);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        json.Append(']');");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static void AppendString(StringBuilder json, string? value)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (value is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            json.Append(\"null\");");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        json.Append('\"');");
        builder.AppendLine("        foreach (char character in value)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (character)");
        builder.AppendLine("            {");
        builder.AppendLine("""
                case '\\': json.Append("\\\\"); break;
                case '"': json.Append("\\\""); break;
                case '\n': json.Append("\\n"); break;
                case '\r': json.Append("\\r"); break;
                case '\t': json.Append("\\t"); break;
                default:
                    if (character < 0x20)
                        json.Append("\\u").Append(((int)character).ToString("x4"));
                    else
                        json.Append(character);
                    break;
""");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        json.Append('\"');");
        builder.AppendLine("    }");
    }

    private static void AppendWrite(StringBuilder builder, string name, string parameter, string body)
    {
        builder.AppendLine($"    private static void {name}(global::System.Collections.Generic.List<byte> buffer, {parameter})");
        builder.AppendLine("    {");
        builder.AppendLine($"        {body}");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendRead(StringBuilder builder, string typeName, string name, string expression, int size)
    {
        builder.AppendLine($"    private static {typeName} {name}(global::System.ReadOnlySpan<byte> data, ref int offset)");
        builder.AppendLine("    {");
        builder.AppendLine($"        if (data.Length - offset < {size})");
        builder.AppendLine("            throw new global::System.InvalidOperationException(\"Truncated character wire.\");");
        builder.AppendLine($"        {typeName} value = {expression};");
        builder.AppendLine($"        offset += {size};");
        builder.AppendLine("        return value;");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string Sanitize(string metadataName)
    {
        var builder = new StringBuilder(metadataName.Length);
        foreach (char character in metadataName)
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');

        return builder.ToString();
    }
}
