<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>

  <Import Project="..\..\src\Logic.Foundation.PreviewManagement.Generators\PreviewPluginAbi.props" />

  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\src\CfgBinEditor\bin\Debug\net8.0\plugins</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\narration.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\narration.png">
      <LogicalName>narration.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Logic.Foundation.PreviewManagement.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Logic.Foundation.PreviewManagement.Abstract\Logic.Foundation.PreviewManagement.Abstract.csproj" />
    <ProjectReference Include="..\plugin_common\plugin_common.csproj" />
  </ItemGroup>

</Project>
