<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>

  <Import Project="..\..\src\Logic.Foundation.PreviewManagement.Generators\PreviewPluginAbi.props" />

  <ItemGroup>
    <None Remove="Resources\narration.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\narration.png">
      <LogicalName>narration.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Logic.Foundation.PreviewManagement.Abstract\Logic.Foundation.PreviewManagement.Abstract.csproj" />
    <ProjectReference Include="..\plugin_common\plugin_common.csproj" />
  </ItemGroup>

</Project>
